//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.UserControls.EastSussexGovUK {
    
    
    public partial class BreadcrumbTrail {
        
        /// <summary>
        /// breadcrumb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EsccWebTeam.EastSussexGovUK.MasterPages.Controls.BreadcrumbTrail breadcrumb;
    }
}
