//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.UserControls {
    
    
    public partial class RelatedLinksMvc {
        
        /// <summary>
        /// related control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl related;
        
        /// <summary>
        /// pages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pages;
        
        /// <summary>
        /// phRelatedPages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phRelatedPages;
        
        /// <summary>
        /// docs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal docs;
        
        /// <summary>
        /// pagesOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder pagesOnly;
        
        /// <summary>
        /// phRelatedPagesOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phRelatedPagesOnly;
        
        /// <summary>
        /// docsOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal docsOnly;
        
        /// <summary>
        /// websites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl websites;
        
        /// <summary>
        /// phRelatedSites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phRelatedSites;
        
        /// <summary>
        /// websitesOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder websitesOnly;
        
        /// <summary>
        /// phRelatedSitesOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phRelatedSitesOnly;
    }
}
