//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Web.Views {
    
    
    public partial class CouncilPlanHomePage {
        
        /// <summary>
        /// phTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phTitle;
        
        /// <summary>
        /// columns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl columns;
        
        /// <summary>
        /// column1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl column1;
        
        /// <summary>
        /// phContent01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent01;
        
        /// <summary>
        /// phImage09 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage09;
        
        /// <summary>
        /// phContent04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent04;
        
        /// <summary>
        /// phImage10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage10;
        
        /// <summary>
        /// phContent05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent05;
        
        /// <summary>
        /// phImage11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage11;
        
        /// <summary>
        /// phContent06 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent06;
        
        /// <summary>
        /// phImage12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage12;
        
        /// <summary>
        /// phContent07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent07;
        
        /// <summary>
        /// phImage13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage13;
        
        /// <summary>
        /// phContent08 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent08;
        
        /// <summary>
        /// phImage14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage14;
        
        /// <summary>
        /// phContent09 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent09;
        
        /// <summary>
        /// phImage15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage15;
        
        /// <summary>
        /// phContent10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent10;
        
        /// <summary>
        /// leader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl leader;
        
        /// <summary>
        /// leaderPhoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl leaderPhoto;
        
        /// <summary>
        /// phLeaderName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phLeaderName;
        
        /// <summary>
        /// chiefExec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl chiefExec;
        
        /// <summary>
        /// chiefExecPhoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl chiefExecPhoto;
        
        /// <summary>
        /// phChiefExecName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phChiefExecName;
        
        /// <summary>
        /// column2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl column2;
        
        /// <summary>
        /// aims control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl aims;
        
        /// <summary>
        /// content3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl content3;
        
        /// <summary>
        /// logos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl logos;
        
        /// <summary>
        /// logo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl logo1;
        
        /// <summary>
        /// logo2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl logo2;
        
        /// <summary>
        /// images control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl images;
        
        /// <summary>
        /// image1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl image1;
        
        /// <summary>
        /// image2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl image2;
        
        /// <summary>
        /// image3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl image3;
        
        /// <summary>
        /// image4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl image4;
    }
}
