//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Web.Views {
    
    
    public partial class LandingPageWithPictures {
        
        /// <summary>
        /// phIntro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phIntro;
        
        /// <summary>
        /// item01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item01;
        
        /// <summary>
        /// phImage01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage01;
        
        /// <summary>
        /// phListTitle01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle01;
        
        /// <summary>
        /// phListDesc01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc01;
        
        /// <summary>
        /// item02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item02;
        
        /// <summary>
        /// phImage02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage02;
        
        /// <summary>
        /// phListTitle02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle02;
        
        /// <summary>
        /// phListDesc02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc02;
        
        /// <summary>
        /// item03 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item03;
        
        /// <summary>
        /// phImage03 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage03;
        
        /// <summary>
        /// phListTitle03 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle03;
        
        /// <summary>
        /// phListDesc03 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc03;
        
        /// <summary>
        /// item04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item04;
        
        /// <summary>
        /// phImage04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage04;
        
        /// <summary>
        /// phListTitle04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle04;
        
        /// <summary>
        /// phListDesc04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc04;
        
        /// <summary>
        /// item05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item05;
        
        /// <summary>
        /// phImage05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage05;
        
        /// <summary>
        /// phListTitle05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle05;
        
        /// <summary>
        /// phListDesc05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc05;
        
        /// <summary>
        /// item06 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item06;
        
        /// <summary>
        /// phImage06 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage06;
        
        /// <summary>
        /// phListTitle06 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle06;
        
        /// <summary>
        /// phListDesc06 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc06;
        
        /// <summary>
        /// item07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item07;
        
        /// <summary>
        /// phImage07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage07;
        
        /// <summary>
        /// phListTitle07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle07;
        
        /// <summary>
        /// phListDesc07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc07;
        
        /// <summary>
        /// item08 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item08;
        
        /// <summary>
        /// phImage08 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage08;
        
        /// <summary>
        /// phListTitle08 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle08;
        
        /// <summary>
        /// phListDesc08 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc08;
        
        /// <summary>
        /// item09 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item09;
        
        /// <summary>
        /// phImage09 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage09;
        
        /// <summary>
        /// phListTitle09 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle09;
        
        /// <summary>
        /// phListDesc09 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc09;
        
        /// <summary>
        /// item10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item10;
        
        /// <summary>
        /// phImage10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage10;
        
        /// <summary>
        /// phListTitle10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle10;
        
        /// <summary>
        /// phListDesc10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc10;
        
        /// <summary>
        /// item11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item11;
        
        /// <summary>
        /// phImage11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage11;
        
        /// <summary>
        /// phListTitle11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle11;
        
        /// <summary>
        /// phListDesc11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc11;
        
        /// <summary>
        /// item12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item12;
        
        /// <summary>
        /// phImage12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage12;
        
        /// <summary>
        /// phListTitle12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle12;
        
        /// <summary>
        /// phListDesc12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc12;
        
        /// <summary>
        /// item13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item13;
        
        /// <summary>
        /// phImage13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage13;
        
        /// <summary>
        /// phListTitle13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle13;
        
        /// <summary>
        /// phListDesc13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc13;
        
        /// <summary>
        /// item14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item14;
        
        /// <summary>
        /// phImage14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage14;
        
        /// <summary>
        /// phListTitle14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle14;
        
        /// <summary>
        /// phListDesc14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc14;
        
        /// <summary>
        /// item15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl item15;
        
        /// <summary>
        /// phImage15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phImage15;
        
        /// <summary>
        /// phListTitle15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListTitle15;
        
        /// <summary>
        /// phListDesc15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phListDesc15;
    }
}
