//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Web.Views {
    
    
    public partial class StandardTopicPage {
        
        /// <summary>
        /// openContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal openContent;
        
        /// <summary>
        /// phIntro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phIntro;
        
        /// <summary>
        /// sections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder sections;
        
        /// <summary>
        /// subtitle7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle7;
        
        /// <summary>
        /// phContent07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent07;
        
        /// <summary>
        /// subtitle8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle8;
        
        /// <summary>
        /// phContent08 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent08;
        
        /// <summary>
        /// subtitle9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle9;
        
        /// <summary>
        /// phContent09 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent09;
        
        /// <summary>
        /// subtitle10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle10;
        
        /// <summary>
        /// phContent10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent10;
        
        /// <summary>
        /// subtitle11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle11;
        
        /// <summary>
        /// phContent11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent11;
        
        /// <summary>
        /// subtitle12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle12;
        
        /// <summary>
        /// phContent12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent12;
        
        /// <summary>
        /// subtitle13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle13;
        
        /// <summary>
        /// phContent13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent13;
        
        /// <summary>
        /// subtitle14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle14;
        
        /// <summary>
        /// phContent14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent14;
        
        /// <summary>
        /// subtitle15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle15;
        
        /// <summary>
        /// phContent15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent15;
        
        /// <summary>
        /// subtitle16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle16;
        
        /// <summary>
        /// phContent16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent16;
        
        /// <summary>
        /// subtitle17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle17;
        
        /// <summary>
        /// phContent17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent17;
        
        /// <summary>
        /// subtitle18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle18;
        
        /// <summary>
        /// phContent18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent18;
        
        /// <summary>
        /// subtitle19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle19;
        
        /// <summary>
        /// phContent19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent19;
        
        /// <summary>
        /// subtitle20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl subtitle20;
        
        /// <summary>
        /// phContent20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phContent20;
        
        /// <summary>
        /// logos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl logos;
        
        /// <summary>
        /// phLogo01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo01;
        
        /// <summary>
        /// phLogo02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo02;
        
        /// <summary>
        /// phLogo03 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo03;
        
        /// <summary>
        /// phLogo04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo04;
        
        /// <summary>
        /// phLogo05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo05;
        
        /// <summary>
        /// phLogo06 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo06;
        
        /// <summary>
        /// phLogo07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo07;
        
        /// <summary>
        /// phLogo08 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.XhtmlImagePlaceholderControl phLogo08;
        
        /// <summary>
        /// endContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal endContent;
    }
}
