//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Api.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.EastSussexGovUK.Umbraco.Api.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hours of work: 32.25 hours per week&lt;br /&gt;
        /// Working pattern: Part-time, Term-time only.&lt;br /&gt;
        /// (As the position is part-time/term-time only, the above salary will be pro rata)&lt;br /&gt;
        /// Fixed term until: July 2019 initially, however may be extended based on nursery pupil numbers.&lt;/p&gt;
        /// 
        /// &lt;p&gt;This role may be filled by two applicants as a job share.&lt;/p&gt;
        /// 
        /// &lt;p&gt;Closing date: Friday 26 April 2019, noon&lt;br /&gt;
        /// Interview date: Week commencing Monday 29 April 2019&lt;/p&gt;
        /// 
        /// &lt;p&gt;For more information and to apply [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BadLinkInHtml {
            get {
                return ResourceManager.GetString("BadLinkInHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;div&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span&gt;Hours of work: Variable/Flexible&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span&gt;Working pattern: Variable/Flexible&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span&gt;Closing date: Sunday 23 April 2017&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span&gt;For an informal discussion, please contact Nicola Spencer - Service Support Officer on 01323 464470.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;/div&gt;&lt;/span&gt;.
        /// </summary>
        internal static string ClosingDateInBody1 {
            get {
                return ResourceManager.GetString("ClosingDateInBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Salary: £48,396 - £55,644 per annum&lt;br /&gt;Contract type: Permanent &lt;br /&gt;Working pattern: Full time&lt;/p&gt;
        ///&lt;p&gt;Closing date: Sunday 24 September 2017&lt;br /&gt;Interview date: week commencing Monday 2 October 2017&lt;/p&gt;
        ///&lt;p&gt;How to apply: please follow the below link:&lt;br /&gt;&lt;a href=&quot;https://www.surreycc.gov.uk/jobs/erecruitment/details.html?nPostingID=19590&amp;nPostingTargetID=44866&amp;option=52&amp;sort=DESC&amp;respnr=1&amp;ID=Q0EFK026203F3VBQB7968LOCX&amp;Resultsperpage=20&amp;lg=UK&amp;mask=surrex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongUrlAndEmailInBodyText {
            get {
                return ResourceManager.GetString("LongUrlAndEmailInBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;job_options&gt;&lt;custom_fields&gt;&lt;question_id&gt;12&lt;/question_id&gt;&lt;label&gt;Reason for Fixed Term/Secondment?&lt;/label&gt;&lt;type&gt;text&lt;/type&gt;&lt;required&gt;&lt;/required&gt;&lt;/custom_fields&gt;&lt;custom_fields&gt;&lt;question_id&gt;13&lt;/question_id&gt;&lt;label&gt;Working Pattern&lt;/label&gt;&lt;type&gt;select&lt;/type&gt;&lt;required&gt;&lt;/required&gt;&lt;options&gt;&lt;id&gt;15&lt;/id&gt;&lt;label&gt;Annualised Hours&lt;/label&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;/options&gt;&lt;options&gt;&lt;id&gt;16&lt;/id&gt;&lt;label&gt;Full Time&lt;/label&gt;&lt;has_jobs&gt;1&lt;/has_jobs&gt;&lt;/options&gt;&lt;options&gt;&lt;id&gt;17&lt;/id&gt;&lt;label&gt;Part Time&lt;/la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadCustomFieldsXml {
            get {
                return ResourceManager.GetString("TribePadCustomFieldsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///    &lt;job&gt;
        ///        &lt;job_id&gt;550&lt;/job_id&gt;
        ///        &lt;job_title&gt;Newly Qualified Social Worker (Children&apos;s Services)&lt;/job_title&gt;
        ///        &lt;reference&gt;orbis/TP/12/550&lt;/reference&gt;
        ///        &lt;language_code&gt;en&lt;/language_code&gt;
        ///        &lt;no_of_positions&gt;30&lt;/no_of_positions&gt;
        ///        &lt;open_date&gt;2019-04-01&lt;/open_date&gt;
        ///        &lt;expiry_date&gt;2019-05-12&lt;/expiry_date&gt;
        ///        &lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///        &lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///        &lt;salary_from&gt;2880 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobMultipleLocationsSeparatedByCommaSpace {
            get {
                return ResourceManager.GetString("TribePadJobMultipleLocationsSeparatedByCommaSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;job_options&gt;&lt;job_categories&gt;&lt;job_category&gt;&lt;id&gt;1&lt;/id&gt;&lt;has_jobs&gt;1&lt;/has_jobs&gt;&lt;name&gt;Administration &amp;amp;amp; Clerical&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;2&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Adult Learning&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;3&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Analyst&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;4&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Apprenticeships &amp;amp;amp; Trainee&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;5&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Architec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobOptionsXml {
            get {
                return ResourceManager.GetString("TribePadJobOptionsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///    &lt;job&gt;
        ///        &lt;job_id&gt;550&lt;/job_id&gt;
        ///        &lt;job_title&gt;Newly Qualified Social Worker (Children&apos;s Services)&lt;/job_title&gt;
        ///        &lt;reference&gt;orbis/TP/12/550&lt;/reference&gt;
        ///        &lt;language_code&gt;en&lt;/language_code&gt;
        ///        &lt;no_of_positions&gt;30&lt;/no_of_positions&gt;
        ///        &lt;open_date&gt;2019-04-01&lt;/open_date&gt;
        ///        &lt;expiry_date&gt;2019-05-12&lt;/expiry_date&gt;
        ///        &lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///        &lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///        &lt;salary_from&gt;2880 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobSingleLocation {
            get {
                return ResourceManager.GetString("TribePadJobSingleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;
        ///    &lt;job&gt;
        ///        &lt;job_id&gt;550&lt;/job_id&gt;
        ///        &lt;job_title&gt;Newly Qualified Social Worker (Children&apos;s Services)&lt;/job_title&gt;
        ///        &lt;reference&gt;orbis/TP/12/550&lt;/reference&gt;
        ///        &lt;language_code&gt;en&lt;/language_code&gt;
        ///        &lt;no_of_positions&gt;30&lt;/no_of_positions&gt;
        ///        &lt;open_date&gt;2019-04-01&lt;/open_date&gt;
        ///        &lt;expiry_date&gt;2019-05-12&lt;/expiry_date&gt;
        ///        &lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///        &lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///        &lt;salary_f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobWith1File {
            get {
                return ResourceManager.GetString("TribePadJobWith1File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;
        ///    &lt;job&gt;
        ///        &lt;job_id&gt;550&lt;/job_id&gt;
        ///        &lt;job_title&gt;Newly Qualified Social Worker (Children&apos;s Services)&lt;/job_title&gt;
        ///        &lt;reference&gt;orbis/TP/12/550&lt;/reference&gt;
        ///        &lt;language_code&gt;en&lt;/language_code&gt;
        ///        &lt;no_of_positions&gt;30&lt;/no_of_positions&gt;
        ///        &lt;open_date&gt;2019-04-01&lt;/open_date&gt;
        ///        &lt;expiry_date&gt;2019-05-12&lt;/expiry_date&gt;
        ///        &lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///        &lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///        &lt;salary_f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobWith2Files {
            get {
                return ResourceManager.GetString("TribePadJobWith2Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_text&gt;&lt;salary_to_text&gt;35&lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobXml {
            get {
                return ResourceManager.GetString("TribePadJobXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;jobs&gt;
        ///&lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///        &lt;reference&gt;orbis/TP/12/550&lt;/reference&gt;
        ///        &lt;language_code&gt;en&lt;/language_code&gt;
        ///        &lt;no_of_positions&gt;30&lt;/no_of_positions&gt;
        ///&lt;open_date&gt;2019-07-12&lt;/open_date&gt;
        ///&lt;expiry_date&gt;0000-00-00&lt;/expiry_date&gt;
        ///&lt;evergreen&gt;1&lt;/evergreen&gt;
        ///        &lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///        &lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///        &lt;salary_from&gt;28802&lt;/salary_from&gt;
        ///        &lt;salary_to&gt;31112&lt;/salary_to&gt;
        ///        &lt;salary_from_text&gt;28 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadNoClosingDate {
            get {
                return ResourceManager.GetString("TribePadNoClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_text&gt;&lt;salary_to_text&gt;35&lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadPartnershipJobXmlOrganisationMissing {
            get {
                return ResourceManager.GetString("TribePadPartnershipJobXmlOrganisationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job (Example Organisation)&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadPartnershipJobXmlWithOrganisation {
            get {
                return ResourceManager.GetString("TribePadPartnershipJobXmlWithOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;23000&lt;/salary_from&gt;
        ///&lt;salary_to&gt;23000&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;23000&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;23000&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£23000 - £23000&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryExact {
            get {
                return ResourceManager.GetString("TribePadSalaryExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;bad&lt;/salary_from&gt;
        ///&lt;salary_to&gt;7503&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;7503.6&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;7503.6&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£7,503.60 per annum&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryFromBadData {
            get {
                return ResourceManager.GetString("TribePadSalaryFromBadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;2&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;19.22&lt;/salary_from&gt;
        ///&lt;salary_to&gt;19.22&lt;/salary_to&gt;
        ///&lt;salaryDisplay&gt;£19.22 per hour&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryHourlyExact {
            get {
                return ResourceManager.GetString("TribePadSalaryHourlyExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;2&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;9.68&lt;/salary_from&gt;
        ///&lt;salary_to&gt;11.2&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;9.68&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;11.2&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£9.68 - £11.20&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryHourlyRange {
            get {
                return ResourceManager.GetString("TribePadSalaryHourlyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;0&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text/&gt;
        ///&lt;salary_to_text/&gt;
        ///&lt;salaryText /&gt;
        ///&lt;custom_15&gt;
        ///&lt;id&gt;1384&lt;/id&gt;
        ///&lt;field_id&gt;15&lt;/field_id&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;answer&gt;36&lt;/answer&gt;
        ///&lt;flags&gt;0&lt;/flags&gt;
        ///&lt;modified_time&gt;2019-01-28 14:54:37&lt;/modified_time&gt;
        ///&lt;/custom_15&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryPayGradeOnly {
            get {
                return ResourceManager.GetString("TribePadSalaryPayGradeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;15000&lt;/salary_from&gt;
        ///&lt;salary_to&gt;19999&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;15000&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;19999&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£15000 - £19999&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryRange {
            get {
                return ResourceManager.GetString("TribePadSalaryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;0&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text/&gt;
        ///&lt;salary_to_text/&gt;
        ///&lt;salaryText&gt;Competitive&lt;/salaryText&gt;
        ///&lt;custom_15&gt;
        ///&lt;id&gt;1384&lt;/id&gt;
        ///&lt;field_id&gt;15&lt;/field_id&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;answer&gt;36&lt;/answer&gt;
        ///&lt;flags&gt;0&lt;/flags&gt;
        ///&lt;modified_time&gt;2019-01-28 14:54:37&lt;/modified_time&gt;
        ///&lt;/custom_15&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryTextOnly {
            get {
                return ResourceManager.GetString("TribePadSalaryTextOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;7503&lt;/salary_from&gt;
        ///&lt;salary_to&gt;bad&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;7503.6&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;7503.6&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£7,503.60 per annum&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryToBadData {
            get {
                return ResourceManager.GetString("TribePadSalaryToBadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;23000&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;23000&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;23000&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£23000&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryToZero {
            get {
                return ResourceManager.GetString("TribePadSalaryToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;0&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text/&gt;
        ///&lt;salary_to_text/&gt;
        ///&lt;salaryDisplay/&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryVoluntary {
            get {
                return ResourceManager.GetString("TribePadSalaryVoluntary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;7503.6&lt;/salary_from&gt;
        ///&lt;salary_to&gt;7503.6&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;7503.6&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;7503.6&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£7,503.60 per annum&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryWithPence {
            get {
                return ResourceManager.GetString("TribePadSalaryWithPence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_text&gt;&lt;salary_to_text&gt;35&lt;/salary_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadWorkPatternFullTime {
            get {
                return ResourceManager.GetString("TribePadWorkPatternFullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;&lt;job_id&gt;158&lt;/job_id&gt;&lt;job_title&gt;Recruitment Analyst&lt;/job_title&gt;&lt;reference&gt;orbis/TP/113/158&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;1&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-21&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-21&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;38260&lt;/salary_from&gt;&lt;salary_to&gt;41142&lt;/salary_to&gt;&lt;salary_from_text&gt;38260&lt;/salary_from_text&gt;&lt;salary_to_text&gt;41142&lt;/salary_to_text&gt;&lt;sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadWorkPatternMissing37Hours {
            get {
                return ResourceManager.GetString("TribePadWorkPatternMissing37Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;video-embed-wrapper&quot; contenteditable=&quot;false&quot;&gt;&lt;iframe allowfullscreen=&quot;&quot; frameborder=&quot;0&quot; height=&quot;100%&quot; mozallowfullscreen=&quot;&quot; src=&quot;//www.youtube.com/embed/1JOsjWX56Kg?showinfo=0&amp;controls=0&amp;rel=0&quot; webkitallowfullscreen=&quot;&quot; width=&quot;100%&quot;&gt;&lt;/iframe&gt;&lt;/div&gt;.
        /// </summary>
        internal static string YouTubeIFrame {
            get {
                return ResourceManager.GetString("YouTubeIFrame", resourceCulture);
            }
        }
    }
}
