//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Api.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.EastSussexGovUK.Umbraco.Api.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hours of work: 32.25 hours per week&lt;br /&gt;
        /// Working pattern: Part-time, Term-time only.&lt;br /&gt;
        /// (As the position is part-time/term-time only, the above salary will be pro rata)&lt;br /&gt;
        /// Fixed term until: July 2019 initially, however may be extended based on nursery pupil numbers.&lt;/p&gt;
        /// 
        /// &lt;p&gt;This role may be filled by two applicants as a job share.&lt;/p&gt;
        /// 
        /// &lt;p&gt;Closing date: Friday 26 April 2019, noon&lt;br /&gt;
        /// Interview date: Week commencing Monday 29 April 2019&lt;/p&gt;
        /// 
        /// &lt;p&gt;For more information and to apply [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BadLinkInHtml {
            get {
                return ResourceManager.GetString("BadLinkInHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;div&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span&gt;Hours of work: Variable/Flexible&lt;/span&gt;&lt;span&gt;&lt;br /&gt;&lt;/span&gt;&lt;span&gt;Working pattern: Variable/Flexible&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span&gt;Closing date: Sunday 23 April 2017&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span&gt;For an informal discussion, please contact Nicola Spencer - Service Support Officer on 01323 464470.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;/div&gt;&lt;/span&gt;.
        /// </summary>
        internal static string ClosingDateInBody1 {
            get {
                return ResourceManager.GetString("ClosingDateInBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;There are permanent contracts available ranging from 18 to 36 hours per week, you will be required to have access to a car and to work alternate weekends and a mix of early and late shifts. Full time staff receive 25 days holiday plus bank holidays. The hourly rate is £9.68.&lt;/p&gt;
        ///&lt;p&gt;Hear first-hand how rewarding this role is by watching this short film of one of our support workers.&lt;/p&gt;.
        /// </summary>
        internal static string HourlyRateInBodyText1 {
            get {
                return ResourceManager.GetString("HourlyRateInBodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot; http://www.w3.org/TR/html4/strict.dtd&quot;&gt;&lt;html lang=&quot;en-GB&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:addthis=&quot;http://www.addthis.com/help/api-spec&quot; &gt;&lt;head&gt;&lt;meta name=&quot;GENERATOR&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;TEMPLATEBASE&quot; content=&quot;Accessible HTML&quot;&gt;&lt;meta name=&quot;LASTUPDATED&quot; content=&quot;18/08/05 10:05:33&quot;&gt;&lt;meta name=&quot;author&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;keywords&quot; content=&quot;Jobs, Career Section, Candidate Portal&quot;&gt;&lt;meta name=&quot;description&quot; content=&quot;Mrted Talentlink syn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobAdvert1Html {
            get {
                return ResourceManager.GetString("JobAdvert1Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;JD-Field1&quot;&gt;
        ///&lt;h5 class=&quot;JD-FieldLabel&quot; id=&quot;JDLabel-Field1&quot;&gt;Job Details&lt;/h5&gt;
        ///&lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;div&gt;
        ///&lt;p&gt;&lt;span style=&quot;font-size: 8.5pt; font-family: &apos;Verdana&apos;,&apos;sans-serif&apos;; color: black;&quot;&gt;Hours of work: Casual hours&lt;br&gt;Working pattern: Part-time&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span style=&quot;font-size: 8.5pt; font-family: &apos;Verdana&apos;,&apos;sans-serif&apos;; color: black;&quot;&gt;Closing date: Sunday&amp;nbsp;29 January 2017&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;&lt;span style=&quot;font-size: 8.5pt; font-family: &apos;Verdana&apos;,&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobDetailInHtml1 {
            get {
                return ResourceManager.GetString("JobDetailInHtml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot; http://www.w3.org/TR/html4/strict.dtd&quot;&gt;&lt;html lang=&quot;en-GB&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:addthis=&quot;http://www.addthis.com/help/api-spec&quot; &gt;&lt;head&gt;&lt;meta name=&quot;GENERATOR&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;TEMPLATEBASE&quot; content=&quot;Accessible HTML&quot;&gt;&lt;meta name=&quot;LASTUPDATED&quot; content=&quot;18/08/05 10:05:33&quot;&gt;&lt;meta name=&quot;author&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;keywords&quot; content=&quot;Jobs, Career Section, Candidate Portal&quot;&gt;&lt;meta name=&quot;description&quot; content=&quot;Mrted Talentlink syn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobResultsOuterHtml {
            get {
                return ResourceManager.GetString("JobResultsOuterHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot; http://www.w3.org/TR/html4/strict.dtd&quot;&gt;&lt;html lang=&quot;en-GB&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:addthis=&quot;http://www.addthis.com/help/api-spec&quot; &gt;&lt;head&gt;&lt;meta name=&quot;GENERATOR&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;TEMPLATEBASE&quot; content=&quot;Accessible HTML&quot;&gt;&lt;meta name=&quot;LASTUPDATED&quot; content=&quot;18/08/05 10:05:33&quot;&gt;&lt;meta name=&quot;author&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;keywords&quot; content=&quot;Jobs, Career Section, Candidate Portal&quot;&gt;&lt;meta name=&quot;description&quot; content=&quot;Mrted Talentlink syn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastPageOfJobs {
            get {
                return ResourceManager.GetString("LastPageOfJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Salary: £48,396 - £55,644 per annum&lt;br /&gt;Contract type: Permanent &lt;br /&gt;Working pattern: Full time&lt;/p&gt;
        ///&lt;p&gt;Closing date: Sunday 24 September 2017&lt;br /&gt;Interview date: week commencing Monday 2 October 2017&lt;/p&gt;
        ///&lt;p&gt;How to apply: please follow the below link:&lt;br /&gt;&lt;a href=&quot;https://www.surreycc.gov.uk/jobs/erecruitment/details.html?nPostingID=19590&amp;nPostingTargetID=44866&amp;option=52&amp;sort=DESC&amp;respnr=1&amp;ID=Q0EFK026203F3VBQB7968LOCX&amp;Resultsperpage=20&amp;lg=UK&amp;mask=surrex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongUrlAndEmailInBodyText {
            get {
                return ResourceManager.GetString("LongUrlAndEmailInBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;Lst-BG1&quot;&gt;
        ///&lt;td headers=&quot;th1&quot; class=&quot;Lst-Desc1T&quot;&gt;
        ///&lt;a href=&quot;jsoutputinitrapido.cfm?component=lay9999_jdesc100a&amp;amp;nPostingID=16476&amp;amp;nPostingTargetID=33720&amp;amp;option=52&amp;amp;sort=DESC&amp;amp;respnr=8&amp;amp;ID=PFOFK026203F3VBQB7968LOH0&amp;amp;Resultsperpage=10&amp;amp;lg=UK&amp;amp;mask=esccext&quot; class=&quot;lstA-desc1&quot; title=&quot;Click here to see the job description: Civil Enforcement Officer (NSL Ltd) (ID33720)&quot; tabindex=&quot;6&quot;&gt;Civil Enforcement Officer (NSL Ltd)&lt;/a&gt;
        ///&lt;/td&gt;
        ///&lt;td headers=&quot;th2&quot; class=&quot;Lst-Desc12&quot;&gt;
        ///Partner [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipleJobResults {
            get {
                return ResourceManager.GetString("MultipleJobResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot; http://www.w3.org/TR/html4/strict.dtd&quot;&gt;&lt;html lang=&quot;en-GB&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:addthis=&quot;http://www.addthis.com/help/api-spec&quot; &gt;&lt;head&gt;&lt;meta name=&quot;GENERATOR&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;TEMPLATEBASE&quot; content=&quot;Accessible HTML&quot;&gt;&lt;meta name=&quot;LASTUPDATED&quot; content=&quot;18/08/05 10:05:33&quot;&gt;&lt;meta name=&quot;author&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;keywords&quot; content=&quot;Jobs, Career Section, Candidate Portal&quot;&gt;&lt;meta name=&quot;description&quot; content=&quot;Mrted Talentlink syn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoJobsResult {
            get {
                return ResourceManager.GetString("NoJobsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Location: Hastings&lt;br&gt;Start date: 01 May 2017&lt;br&gt;Salary: Ark Leadership Scale L1 – L5 (£38, 984 - £43, 022)&lt;br&gt;Closing date: 9am on Monday 20 February 2017&lt;br&gt;Interview date: Thursday 23 February 2017&lt;br&gt;&lt;br&gt;Ark Blacklands and Ark Little Ridge Primary Academies are committed to safeguarding children; successful candidates will be subject to an enhanced Disclosure &amp;amp; Barring Service check.&lt;/p&gt;.
        /// </summary>
        internal static string TalentLinkSalaryInBodyText1 {
            get {
                return ResourceManager.GetString("TalentLinkSalaryInBodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field2&quot;&gt;&lt;p&gt;QUALITY OFFICER &lt;br&gt;&lt;br&gt;£16,692 - £17,808 per annum&amp;nbsp;(Full-time/full year).&lt;/p&gt;
        ///&lt;p&gt;We are looking for a well-qualified, enthusiastic team player with excellent communication, administration and IT skills.&amp;nbsp; Key elements of this role will be managing the administration of the College’s quality management systems, preparing reports, setting up online surveys and other quality measures; and providing an analysis of the results.&amp;nbsp; You will need to ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TalentLinkSalaryInBodyText2 {
            get {
                return ResourceManager.GetString("TalentLinkSalaryInBodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Salary: To be negotiated&lt;br&gt;Contract type: Permanent&lt;br&gt;Working pattern: Part time&lt;/p&gt;.
        /// </summary>
        internal static string TalentLinkSalaryInBodyText3 {
            get {
                return ResourceManager.GetString("TalentLinkSalaryInBodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5 class=&quot;JD-FieldLabel&quot; id=&quot;JDLabel-Field1&quot;&gt;Job Details&lt;/h5&gt;
        ///&lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Salary: Dependant on experience, knowledge and qualifications&lt;br /&gt;Contract type: Part Time&lt;br /&gt;Working pattern: 20-30 hours per week&lt;/p&gt;
        ///&lt;p&gt;Closing date: Thursday 31 August 2017&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;Applicants can send their CV to &lt;a href=&quot;mailto:director@twigletsforestschoolnursery.com&quot;&gt;director@twigletsforestschoolnursery.com&lt;/a&gt;&amp;nbsp;Once CV is received, an application form will be emailed.&lt;br /&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TalentLinkSalaryInBodyText4 {
            get {
                return ResourceManager.GetString("TalentLinkSalaryInBodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5 class=&quot;JD-FieldLabel&quot; id=&quot;JDLabel-Field1&quot;&gt;Job Details&lt;/h5&gt;
        ///&lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Salary: £11.79 - £12.51 per hour&lt;br /&gt;Contract type: Part Time&lt;br /&gt;Working pattern: 20-30 hours per week&lt;/p&gt;
        ///&lt;p&gt;Closing date: Thursday 31 August 2017&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;Applicants can send their CV to &lt;a href=&quot;mailto:director@twigletsforestschoolnursery.com&quot;&gt;director@twigletsforestschoolnursery.com&lt;/a&gt;&amp;nbsp;Once CV is received, an application form will be emailed.&lt;br /&gt;&lt;br /&gt;If you have any question [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TalentLinkSalaryInBodyText5 {
            get {
                return ResourceManager.GetString("TalentLinkSalaryInBodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Salary: £22,912 rising to £33,487 per annum (Gildredge House Main Pay Scale points M1-M6, 2018-19) Note: salary figures include a cost of living increase of 1% which is subject to variation. Upper Pay Scale may be accessible to the suitable applicant. The Teacher Responsible for KS4 Mathematics position attracts a further Leadership Allowance point on the GH Scale of £4,204 per annum.  &lt;br /&gt;&lt;br /&gt;Working pattern: Full-Time&lt;/p&gt;
        ///&lt;p&gt;Closing date:  Thursday 15  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TalentLinkSalaryInBodyText6 {
            get {
                return ResourceManager.GetString("TalentLinkSalaryInBodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot; http://www.w3.org/TR/html4/strict.dtd&quot;&gt;&lt;html lang=&quot;en-GB&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:addthis=&quot;http://www.addthis.com/help/api-spec&quot; &gt;&lt;head&gt;&lt;meta name=&quot;GENERATOR&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;TEMPLATEBASE&quot; content=&quot;Accessible HTML&quot;&gt;&lt;meta name=&quot;LASTUPDATED&quot; content=&quot;18/08/05 10:05:33&quot;&gt;&lt;meta name=&quot;author&quot; content=&quot;MrTed&quot;&gt;&lt;meta name=&quot;keywords&quot; content=&quot;Jobs, Career Section, Candidate Portal&quot;&gt;&lt;meta name=&quot;description&quot; content=&quot;Mrted Talentlink syn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TalentLinkSearchFieldsOuterHtml {
            get {
                return ResourceManager.GetString("TalentLinkSearchFieldsOuterHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;job_options&gt;&lt;custom_fields&gt;&lt;question_id&gt;12&lt;/question_id&gt;&lt;label&gt;Reason for Fixed Term/Secondment?&lt;/label&gt;&lt;type&gt;text&lt;/type&gt;&lt;required&gt;&lt;/required&gt;&lt;/custom_fields&gt;&lt;custom_fields&gt;&lt;question_id&gt;13&lt;/question_id&gt;&lt;label&gt;Working Pattern&lt;/label&gt;&lt;type&gt;select&lt;/type&gt;&lt;required&gt;&lt;/required&gt;&lt;options&gt;&lt;id&gt;15&lt;/id&gt;&lt;label&gt;Annualised Hours&lt;/label&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;/options&gt;&lt;options&gt;&lt;id&gt;16&lt;/id&gt;&lt;label&gt;Full Time&lt;/label&gt;&lt;has_jobs&gt;1&lt;/has_jobs&gt;&lt;/options&gt;&lt;options&gt;&lt;id&gt;17&lt;/id&gt;&lt;label&gt;Part Time&lt;/la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadCustomFieldsXml {
            get {
                return ResourceManager.GetString("TribePadCustomFieldsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;job_options&gt;&lt;job_categories&gt;&lt;job_category&gt;&lt;id&gt;1&lt;/id&gt;&lt;has_jobs&gt;1&lt;/has_jobs&gt;&lt;name&gt;Administration &amp;amp;amp; Clerical&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;2&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Adult Learning&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;3&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Analyst&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;4&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Apprenticeships &amp;amp;amp; Trainee&lt;/name&gt;&lt;/job_category&gt;&lt;job_category&gt;&lt;id&gt;5&lt;/id&gt;&lt;has_jobs&gt;0&lt;/has_jobs&gt;&lt;name&gt;Architec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobOptionsXml {
            get {
                return ResourceManager.GetString("TribePadJobOptionsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;
        ///    &lt;job&gt;
        ///        &lt;job_id&gt;550&lt;/job_id&gt;
        ///        &lt;job_title&gt;Newly Qualified Social Worker (Children&apos;s Services)&lt;/job_title&gt;
        ///        &lt;reference&gt;orbis/TP/12/550&lt;/reference&gt;
        ///        &lt;language_code&gt;en&lt;/language_code&gt;
        ///        &lt;no_of_positions&gt;30&lt;/no_of_positions&gt;
        ///        &lt;open_date&gt;2019-04-01&lt;/open_date&gt;
        ///        &lt;expiry_date&gt;2019-05-12&lt;/expiry_date&gt;
        ///        &lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///        &lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///        &lt;salary_f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobWith1File {
            get {
                return ResourceManager.GetString("TribePadJobWith1File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;
        ///    &lt;job&gt;
        ///        &lt;job_id&gt;550&lt;/job_id&gt;
        ///        &lt;job_title&gt;Newly Qualified Social Worker (Children&apos;s Services)&lt;/job_title&gt;
        ///        &lt;reference&gt;orbis/TP/12/550&lt;/reference&gt;
        ///        &lt;language_code&gt;en&lt;/language_code&gt;
        ///        &lt;no_of_positions&gt;30&lt;/no_of_positions&gt;
        ///        &lt;open_date&gt;2019-04-01&lt;/open_date&gt;
        ///        &lt;expiry_date&gt;2019-05-12&lt;/expiry_date&gt;
        ///        &lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///        &lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///        &lt;salary_f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobWith2Files {
            get {
                return ResourceManager.GetString("TribePadJobWith2Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_text&gt;&lt;salary_to_text&gt;35&lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadJobXml {
            get {
                return ResourceManager.GetString("TribePadJobXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_text&gt;&lt;salary_to_text&gt;35&lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadPartnershipJobXmlOrganisationMissing {
            get {
                return ResourceManager.GetString("TribePadPartnershipJobXmlOrganisationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobs&gt;&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job (Example Organisation)&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadPartnershipJobXmlWithOrganisation {
            get {
                return ResourceManager.GetString("TribePadPartnershipJobXmlWithOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;23000&lt;/salary_from&gt;
        ///&lt;salary_to&gt;23000&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;23000&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;23000&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£23000 - £23000&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryExact {
            get {
                return ResourceManager.GetString("TribePadSalaryExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;bad&lt;/salary_from&gt;
        ///&lt;salary_to&gt;7503&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;7503.6&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;7503.6&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£7,503.60 per annum&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryFromBadData {
            get {
                return ResourceManager.GetString("TribePadSalaryFromBadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;2&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;19.22&lt;/salary_from&gt;
        ///&lt;salary_to&gt;19.22&lt;/salary_to&gt;
        ///&lt;salaryDisplay&gt;£19.22 per hour&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryHourlyExact {
            get {
                return ResourceManager.GetString("TribePadSalaryHourlyExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;2&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;9.68&lt;/salary_from&gt;
        ///&lt;salary_to&gt;11.2&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;9.68&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;11.2&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£9.68 - £11.20&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryHourlyRange {
            get {
                return ResourceManager.GetString("TribePadSalaryHourlyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;0&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text/&gt;
        ///&lt;salary_to_text/&gt;
        ///&lt;salaryText /&gt;
        ///&lt;custom_15&gt;
        ///&lt;id&gt;1384&lt;/id&gt;
        ///&lt;field_id&gt;15&lt;/field_id&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;answer&gt;36&lt;/answer&gt;
        ///&lt;flags&gt;0&lt;/flags&gt;
        ///&lt;modified_time&gt;2019-01-28 14:54:37&lt;/modified_time&gt;
        ///&lt;/custom_15&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryPayGradeOnly {
            get {
                return ResourceManager.GetString("TribePadSalaryPayGradeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;15000&lt;/salary_from&gt;
        ///&lt;salary_to&gt;19999&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;15000&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;19999&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£15000 - £19999&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryRange {
            get {
                return ResourceManager.GetString("TribePadSalaryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;0&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text/&gt;
        ///&lt;salary_to_text/&gt;
        ///&lt;salaryText&gt;Competitive&lt;/salaryText&gt;
        ///&lt;custom_15&gt;
        ///&lt;id&gt;1384&lt;/id&gt;
        ///&lt;field_id&gt;15&lt;/field_id&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;answer&gt;36&lt;/answer&gt;
        ///&lt;flags&gt;0&lt;/flags&gt;
        ///&lt;modified_time&gt;2019-01-28 14:54:37&lt;/modified_time&gt;
        ///&lt;/custom_15&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryTextOnly {
            get {
                return ResourceManager.GetString("TribePadSalaryTextOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;7503&lt;/salary_from&gt;
        ///&lt;salary_to&gt;bad&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;7503.6&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;7503.6&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£7,503.60 per annum&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryToBadData {
            get {
                return ResourceManager.GetString("TribePadSalaryToBadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;23000&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;23000&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;23000&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£23000&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryToZero {
            get {
                return ResourceManager.GetString("TribePadSalaryToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;0&lt;/salary_from&gt;
        ///&lt;salary_to&gt;0&lt;/salary_to&gt;
        ///&lt;salary_from_text/&gt;
        ///&lt;salary_to_text/&gt;
        ///&lt;salaryDisplay/&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryVoluntary {
            get {
                return ResourceManager.GetString("TribePadSalaryVoluntary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///&lt;job_id&gt;134&lt;/job_id&gt;
        ///&lt;job_title&gt;New Worker&lt;/job_title&gt;
        ///&lt;salary_currency&gt;1&lt;/salary_currency&gt;
        ///&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;
        ///&lt;salary_from&gt;7503.6&lt;/salary_from&gt;
        ///&lt;salary_to&gt;7503.6&lt;/salary_to&gt;
        ///&lt;salary_from_text&gt;7503.6&lt;/salary_from_text&gt;
        ///&lt;salary_to_text&gt;7503.6&lt;/salary_to_text&gt;
        ///&lt;salaryDisplay&gt;£7,503.60 per annum&lt;/salaryDisplay&gt;
        ///&lt;/job&gt;.
        /// </summary>
        internal static string TribePadSalaryWithPence {
            get {
                return ResourceManager.GetString("TribePadSalaryWithPence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;job&gt;&lt;job_id&gt;142&lt;/job_id&gt;&lt;job_title&gt;Job&lt;/job_title&gt;&lt;reference&gt;orbis/TP/12/142&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;2&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-11&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-11&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;34&lt;/salary_from&gt;&lt;salary_to&gt;35&lt;/salary_to&gt;&lt;salary_from_text&gt;34&lt;/salary_from_text&gt;&lt;salary_to_text&gt;35&lt;/salary_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadWorkPatternFullTime {
            get {
                return ResourceManager.GetString("TribePadWorkPatternFullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;&lt;job_id&gt;158&lt;/job_id&gt;&lt;job_title&gt;Recruitment Analyst&lt;/job_title&gt;&lt;reference&gt;orbis/TP/113/158&lt;/reference&gt;&lt;language_code&gt;en&lt;/language_code&gt;&lt;no_of_positions&gt;1&lt;/no_of_positions&gt;&lt;status&gt;1&lt;/status&gt;&lt;status_social&gt;0&lt;/status_social&gt;&lt;open_date&gt;2019-01-21&lt;/open_date&gt;&lt;expiry_date&gt;2019-02-21&lt;/expiry_date&gt;&lt;salary_currency&gt;1&lt;/salary_currency&gt;&lt;salary_frequency&gt;1&lt;/salary_frequency&gt;&lt;salary_from&gt;38260&lt;/salary_from&gt;&lt;salary_to&gt;41142&lt;/salary_to&gt;&lt;salary_from_text&gt;38260&lt;/salary_from_text&gt;&lt;salary_to_text&gt;41142&lt;/salary_to_text&gt;&lt;sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribePadWorkPatternMissing37Hours {
            get {
                return ResourceManager.GetString("TribePadWorkPatternMissing37Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Salary: £31,383 to £41,373 per annum&lt;br&gt;Contract type: Permanent&lt;br&gt;Working pattern: Full time&lt;/p&gt;
        ///&lt;p&gt;Closing date: Monday 20 February 2017&lt;/p&gt;
        ///&lt;p&gt;How to apply: Please visit &lt;a href=&quot;https://www.jobs.nhs.uk/xi/vacancy/df348e0c47e47974b4d05e3fdff2f5da/?vac_ref=914491197&quot; rel=&quot;external&quot;&gt;https://www.jobs.nhs.uk/xi/vacancy/df348e0c47e47974b4d05e3fdff2f5da/?vac_ref=914491197&lt;/a&gt;&lt;/p&gt;&lt;/span&gt;.
        /// </summary>
        internal static string WorkPatternInBodyText1 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;JD-Field1&quot;&gt;
        ///&lt;h5 class=&quot;JD-FieldLabel&quot; id=&quot;JDLabel-Field1&quot;&gt;Job Details&lt;/h5&gt;
        ///&lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;div&gt;
        ///&lt;p&gt;Hours of work: Up to 37 hours per week&lt;br&gt;&lt;br&gt;Closing date: Sunday 05 February 2017&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;For an&amp;nbsp;informal discussion, please contact Tim Proudlock - Service Support Officer on 01323 747433.&lt;/p&gt;
        ///&lt;/div&gt;&lt;/span&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string WorkPatternInBodyText10 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Salary: £34,981 - £40,180 per annum, pro rata - dependent on qualification, skill &amp;amp; experience&lt;br&gt;Contract type: Permanent&lt;br&gt;Working pattern: 25 - 37 hours per week&lt;/p&gt;
        ///&lt;p&gt;Closing date: Wednesday 13 February 2017&lt;/p&gt;
        ///&lt;p&gt;How to apply: To download an application pack please visit: &lt;a href=&quot;http://sussexcommunity.org.uk/about-us/jobs/&quot; rel=&quot;external&quot;&gt;http://sussexcommunity.org.uk/about-us/jobs/&lt;/a&gt;&lt;/p&gt;&lt;/span&gt;.
        /// </summary>
        internal static string WorkPatternInBodyText2 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;Hours of work: Teacher&apos;s full time hours&lt;br&gt;Working pattern: Full-time&lt;br&gt;Fixed term to cover Maternity&lt;/p&gt;
        ///&lt;p&gt;Closing date: Monday 06 February 2017 at 5.00pm&lt;br&gt;Interview date: Tuesday 07 February 2017&lt;/p&gt;
        ///&lt;p&gt;For more information and to apply for the above post, please contact:&lt;/p&gt;
        ///&lt;p&gt;Maynards Green CP School&lt;br&gt;Maynards Green&lt;br&gt;Heathfield&lt;br&gt;East Sussex&lt;br&gt;TN21 0DD&lt;/p&gt;
        ///&lt;p&gt;Phone: 01435 812622&lt;br&gt;Fax:&amp;nbsp; 01435 813944&lt;br&gt;Email: &lt;a href=&quot;mailto:office@m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkPatternInBodyText3 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;div&gt;
        ///&lt;p&gt;Hours of work: 37 hours per week&lt;br&gt;&lt;br&gt;Closing date: Sunday 05 February 2017&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;For an&amp;nbsp;informal discussion, please contact Tim Proudlock - Service Support Officer on 01323 747433.&lt;/p&gt;
        ///&lt;/div&gt;&lt;/span&gt;.
        /// </summary>
        internal static string WorkPatternInBodyText4 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;div&gt;
        ///&lt;p&gt;Hours of work: Usually Saturdays 9:00am to 1:00pm, and some evenings when required.&lt;br&gt;Working pattern: Casual, part-time.&lt;/p&gt;
        ///&lt;p&gt;&lt;br&gt;Closing date: Sunday 05 February 2017.&lt;br&gt;Interview date: Tuesday 21 February 2017.&lt;/p&gt;
        ///&lt;p&gt;For an&amp;nbsp;informal discussion, please contact&amp;nbsp;Leon Maxwell&amp;nbsp;- YOT Practice Manager on 01323 464004 or 07710 710 834.&lt;/p&gt;
        ///&lt;/div&gt;&lt;/span&gt;.
        /// </summary>
        internal static string WorkPatternInBodyText5 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;&lt;img src=&quot;https://eastsussexgovuk.blob.core.windows.net/media/4180/rye-academy-april-2015.jpg&quot; alt=&quot;Rye Academy Trust logo&quot; width=&quot;30%&quot; height=&quot;30%&quot;&gt;&lt;/p&gt;
        ///&lt;p&gt;Hours of work: Full or part time&lt;/p&gt;
        ///&lt;p&gt;(If the position is part-time, the above salary will be pro rata)&lt;/p&gt;
        ///&lt;p&gt;Fixed term until 31 August 2017&lt;/p&gt;
        ///&lt;p&gt;Closing date: Tuesday 31 January 2017&lt;/p&gt;
        ///&lt;p&gt;Please contact Jane Loveless by emailing &lt;a href=&quot;mailto:jloveless@ryecollege.co.uk&quot;&gt;jloveless@ryecolleg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkPatternInBodyText6 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;JD-Field1&quot;&gt;
        ///&lt;h5 class=&quot;JD-FieldLabel&quot; id=&quot;JDLabel-Field1&quot;&gt;Job Details&lt;/h5&gt;
        ///&lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;div&gt;
        ///&lt;p&gt;Hours of work: 13 hours per week (0.4 FTE)&lt;br&gt;Working pattern: Part time&lt;/p&gt;
        ///&lt;p&gt;Fixed term until 31 August 2017&lt;/p&gt;
        ///&lt;p&gt;Closing date: Friday 03 February 2017&lt;br&gt;Interview date: Thursday 09 February 2017&lt;/p&gt;
        ///&lt;p&gt;If you would like to view the school prior to making an application please call the office on 01424 838323 to make an appointment.&lt;/p&gt;
        ///&lt;p&gt;Please go to &lt;a hre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkPatternInBodyText7 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;JD-Field1&quot;&gt;
        ///&lt;h5 class=&quot;JD-FieldLabel&quot; id=&quot;JDLabel-Field1&quot;&gt;Job Details&lt;/h5&gt;
        ///&lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;&lt;span style=&quot;font-size: small; font-family: arial,helvetica,sans-serif;&quot;&gt;Hours of work: Casual&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: small; font-family: arial,helvetica,sans-serif;&quot;&gt;Working pattern: Casual&lt;/span&gt;&lt;br&gt;&lt;br&gt;&lt;span style=&quot;font-size: small; font-family: arial,helvetica,sans-serif;&quot;&gt;Closing date: Monday 06 February 2017&lt;/span&gt;&lt;br&gt;&lt;br&gt;&lt;span style=&quot;font-size: small; font- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkPatternInBodyText8 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;JD-AllFields&quot;&gt;
        ///&lt;div id=&quot;JD-Field1&quot;&gt;
        ///&lt;h5 class=&quot;JD-FieldLabel&quot; id=&quot;JDLabel-Field1&quot;&gt;Job Details&lt;/h5&gt;
        ///&lt;span class=&quot;JD-FieldText&quot; id=&quot;JDText-Field1&quot;&gt;&lt;p&gt;&lt;img src=&quot;https://eastsussexgovuk.blob.core.windows.net/media/7511/step.png&quot; alt=&quot;STEP logo &quot;&gt;&lt;/p&gt;
        ///&lt;p&gt;Hours of work: teacher full time hours&lt;/p&gt;
        ///&lt;p&gt;Closing date: March 31 2017 at 12 noon - Applications will be considered upon receipt.&lt;/p&gt;
        ///&lt;p&gt;For more information and to apply for the above post, please contact:&lt;/p&gt;
        ///&lt;p&gt;Hawkes Farm Academy&lt;br&gt;Hawkes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkPatternInBodyText9 {
            get {
                return ResourceManager.GetString("WorkPatternInBodyText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;video-embed-wrapper&quot; contenteditable=&quot;false&quot;&gt;&lt;iframe allowfullscreen=&quot;&quot; frameborder=&quot;0&quot; height=&quot;100%&quot; mozallowfullscreen=&quot;&quot; src=&quot;//www.youtube.com/embed/1JOsjWX56Kg?showinfo=0&amp;controls=0&amp;rel=0&quot; webkitallowfullscreen=&quot;&quot; width=&quot;100%&quot;&gt;&lt;/iframe&gt;&lt;/div&gt;.
        /// </summary>
        internal static string YouTubeIFrame {
            get {
                return ResourceManager.GetString("YouTubeIFrame", resourceCulture);
            }
        }
    }
}
