//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlaceholderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaceholderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.EastSussexGovUK.Umbraco.Web.MicrosoftCmsMigration.Placeholders.PlaceholderRe" +
                            "sources", typeof(PlaceholderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word format.
        /// </summary>
        internal static string AttachmentFormatDOC {
            get {
                return ResourceManager.GetString("AttachmentFormatDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3 format.
        /// </summary>
        internal static string AttachmentFormatMP3 {
            get {
                return ResourceManager.GetString("AttachmentFormatMP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobat format.
        /// </summary>
        internal static string AttachmentFormatPDF {
            get {
                return ResourceManager.GetString("AttachmentFormatPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich text format.
        /// </summary>
        internal static string AttachmentFormatRTF {
            get {
                return ResourceManager.GetString("AttachmentFormatRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel format.
        /// </summary>
        internal static string AttachmentFormatXLS {
            get {
                return ResourceManager.GetString("AttachmentFormatXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobat format.
        /// </summary>
        internal static string FormatPdf {
            get {
                return ResourceManager.GetString("FormatPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich text format.
        /// </summary>
        internal static string FormatRtf {
            get {
                return ResourceManager.GetString("FormatRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich text format.
        /// </summary>
        internal static string FormatRtfAndSign {
            get {
                return ResourceManager.GetString("FormatRtfAndSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print, write and post.
        /// </summary>
        internal static string FormAttachmentPdf {
            get {
                return ResourceManager.GetString("FormAttachmentPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the form, fill it in in pen and post it to us.
        /// </summary>
        internal static string FormAttachmentPdfTitle {
            get {
                return ResourceManager.GetString("FormAttachmentPdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email it to us.
        /// </summary>
        internal static string FormAttachmentRtf {
            get {
                return ResourceManager.GetString("FormAttachmentRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type, sign and post.
        /// </summary>
        internal static string FormAttachmentRtfAndSign {
            get {
                return ResourceManager.GetString("FormAttachmentRtfAndSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the form on your computer, print it, sign it and post it to us.
        /// </summary>
        internal static string FormAttachmentRtfAndSignTitle {
            get {
                return ResourceManager.GetString("FormAttachmentRtfAndSignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the form on your computer and email it to us.
        /// </summary>
        internal static string FormAttachmentRtfTitle {
            get {
                return ResourceManager.GetString("FormAttachmentRtfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload it securely.
        /// </summary>
        internal static string FormAttachmentUpload {
            get {
                return ResourceManager.GetString("FormAttachmentUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do it online.
        /// </summary>
        internal static string FormAttachmentXhtml {
            get {
                return ResourceManager.GetString("FormAttachmentXhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email it to us.
        /// </summary>
        internal static string FormAttachmentXls {
            get {
                return ResourceManager.GetString("FormAttachmentXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print, write and post.
        /// </summary>
        internal static string FormAttachmentXlsPrint {
            get {
                return ResourceManager.GetString("FormAttachmentXlsPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the figures on your computer, print them and post them it to us.
        /// </summary>
        internal static string FormAttachmentXlsPrintTitle {
            get {
                return ResourceManager.GetString("FormAttachmentXlsPrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the figures on your computer and email them to us.
        /// </summary>
        internal static string FormAttachmentXlsTitle {
            get {
                return ResourceManager.GetString("FormAttachmentXlsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel format.
        /// </summary>
        internal static string FormatXls {
            get {
                return ResourceManager.GetString("FormatXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel format.
        /// </summary>
        internal static string FormatXlsPrint {
            get {
                return ResourceManager.GetString("FormatXlsPrint", resourceCulture);
            }
        }
    }
}
