//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.EastSussexGovUK.Umbraco.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Url&quot;:&quot;https://www.example.org/56070/CSD01592/instrumental-and-vocal-teacher/countywide&quot;,&quot;JobTitle&quot;:&quot;Instrumental and Vocal Teacher&quot;,&quot;Organisation&quot;:&quot;East Sussex County Council&quot;,&quot;Location&quot;:&quot;Countywide&quot;,&quot;Salary&quot;:{&quot;MinimumSalary&quot;:16461,&quot;MaximumSalary&quot;:33160,&quot;SalaryRange&quot;:&quot;£16,461 to £33,160 per annum&quot;,&quot;SearchRange&quot;:&quot;Teachers&apos; Pay Scale&quot;},&quot;ClosingDate&quot;:&quot;2018-04-01T00:00:00+01:00&quot;,&quot;Id&quot;:56070,&quot;Reference&quot;:&quot;CSD01592&quot;,&quot;AdditionalInformationHtml&quot;:&quot;&lt;div&gt;\n&lt;p&gt;This post is subject to an Enhanced DBS check or Enhanced c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobAdvertJson {
            get {
                return ResourceManager.GetString("JobAdvertJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tab2content&quot; aria-labelledby=&quot;tab2&quot; role=&quot;tabpanel&quot; aria-hidden=&quot;true&quot;&gt;
        ///                            &lt;h2 class=&quot;aural&quot;&gt;Equal opportunities&lt;/h2&gt;
        ///                            &lt;div&gt;
        ///&lt;p&gt;&lt;small&gt;East Sussex County Council is an equal opportunities employer. We welcome applications from all suitable candidates, regardless of race, gender, sexual orientation, disability or age. All applications are treated on merit.&lt;/small&gt;&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;p&gt;&lt;small&gt;&lt;img src=&quot;https://example.blob.core.windows.net/media/8880/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MediaDomainsInJobHtml {
            get {
                return ResourceManager.GetString("MediaDomainsInJobHtml", resourceCulture);
            }
        }
    }
}
