//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.Umbraco.Views {
    
    
    public partial class FormDownloadPage {
        
        /// <summary>
        /// latest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.UserControls.Latest latest;
        
        /// <summary>
        /// phIntro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phIntro;
        
        /// <summary>
        /// guidance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder guidance;
        
        /// <summary>
        /// phGuidance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phGuidance;
        
        /// <summary>
        /// guidanceNotes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl guidanceNotes;
        
        /// <summary>
        /// guidance1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.XhtmlAttachmentPlaceholderControl guidance1;
        
        /// <summary>
        /// guidance2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.XhtmlAttachmentPlaceholderControl guidance2;
        
        /// <summary>
        /// guidance3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.XhtmlAttachmentPlaceholderControl guidance3;
        
        /// <summary>
        /// guidance4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.XhtmlAttachmentPlaceholderControl guidance4;
        
        /// <summary>
        /// guidance5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.XhtmlAttachmentPlaceholderControl guidance5;
        
        /// <summary>
        /// formatHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl formatHeading;
        
        /// <summary>
        /// fourWays control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal fourWays;
        
        /// <summary>
        /// phXhtml control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.FormUrlPlaceholderControl phXhtml;
        
        /// <summary>
        /// phUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.FormUrlPlaceholderControl phUpload;
        
        /// <summary>
        /// phPdf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.FormAttachmentPlaceholderControl phPdf;
        
        /// <summary>
        /// phXlsPrint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.FormAttachmentPlaceholderControl phXlsPrint;
        
        /// <summary>
        /// phRtfSign control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.FormAttachmentPlaceholderControl phRtfSign;
        
        /// <summary>
        /// phRtf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.FormAttachmentPlaceholderControl phRtf;
        
        /// <summary>
        /// phXls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.FormAttachmentPlaceholderControl phXls;
        
        /// <summary>
        /// phFootnote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.Umbraco.MicrosoftCmsMigration.Placeholders.RichHtmlPlaceholderControl phFootnote;
        
        /// <summary>
        /// privacy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl privacy;
    }
}
